### PR TITLE
Implements to display ytick

### PR DESCRIPTION
**Pull request by 284km**
I implement it so that ytick is displayed.

ytick is now displayed. But I couldn't control the direction in which ytick was displayed as in the image below.

magick_small_stacked_bar

I thought about a concrete collaboration plan with charty, but I could not draw any conclusions yet.
I have read the rubyplot code, so I tried implementing.

### CODE REVIEW

**Comment by v0dro** [comment]
This is great! What's also great is that you could easily change the code so I think the architecture is pretty good as of now :smile: 

However, there is one small problem. The Y ticks in your example are showing as vertical lines. Could you please change the `YTick` class so that the line is drawing horizontally.

**Comment by v0dro** [comment]
@284km can you please send the corrections to the master branch?

**Comment by 284km** [comment]
OK, I will send again to master branch after fix.

**Comment by 284km** [comment]
I fixed and sent new PR #33 to master. so close this PR.

**Pull request closed without merging**
